name: cefibook
channels:
  - default
dependencies:
  - python=3.10
  - jupyterlab
  - netcdf4
  - erddapy=1.2.1
  - scipy
  - xarray
  - matplotlib
  - folium
  - bokeh
  - plotly
  - r-irkernel
  - r-rerddap
  - pip
  - pip:
    - jupyter-book
    - jupytext
    - ghp-import