name: cefi-cookbook
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - dask
  - netcdf4
  - erddapy=1.2.1
  - scipy
  - xarray
  - cf_xarray
  - matplotlib
  - folium
  - bokeh
  - plotly
  - cartopy
  - zarr
  - fsspec
  - gcsfs
  - s3fs
  - r-maps
  - r-reticulate
  - r-dplyr
  - r-ggplot2
