name: cefi-cookbook
channels:
  - conda-forge
dependencies:
  - python=3.10
  - dask
  - netcdf4
  - erddapy=1.2.1
  - scipy
  - xarray
  - matplotlib
  - folium
  - bokeh
  - plotly
  - r-irkernel=1.3.1
  - r-rerddap
  - r-ncdf4